### ISSUE TITLE
可以添加一个一键导出长图分享的功能

### ISSUE THREAD

**Issue by reKelin** [SHUAXINDIARY/Arknights#9]
如题

**Comment by SHUAXINDIARY** [comment]
> 如题

在做呢，本来是加上了的，但是实际导出后的效果，感觉有点模糊，在研究更高清的一些方案，后续会上

**Comment by novelyear** [comment]
> > 如题
> 
> 在做呢，本来是加上了的，但是实际导出后的效果，感觉有点模糊，在研究更高清的一些方案，后续会上

### 问题描述 / 改动请求

您好！我很喜欢这个项目，但是第一次接触前端，试着加了截图导出的功能，将原来的dom-to-image换成了html2canvas，清晰度提高了一点。
但是有很多问题，尚不足以提交一个完整的 PR。我在这里附上了我的改动，想请您看一下，看看是否有改进的空间或建议。

### 改动内容
https://github.com/SHUAXINDIARY/Arknights/commit/6f919d1a2e6da07843f647a5d21c9ea07db64484

### 为什么没有提交 PR
截图的TextCard文字错位，图片没有margin

例图：
![image](https://github.com/user-attachments/assets/809cd7ef-1c1f-411c-8685-a0ba99c194a2)

如果您有时间，非常感谢你查看我的改动！

谢谢！

**Comment by SHUAXINDIARY** [comment]
> > > 如题
> > 
> > 
> > 在做呢，本来是加上了的，但是实际导出后的效果，感觉有点模糊，在研究更高清的一些方案，后续会上
> 
> ### 问题描述 / 改动请求
> 您好！我很喜欢这个项目，但是第一次接触前端，试着加了截图导出的功能，将原来的dom-to-image换成了html2canvas，清晰度提高了一点。 但是有很多问题，尚不足以提交一个完整的 PR。我在这里附上了我的改动，想请您看一下，看看是否有改进的空间或建议。
> 
> ### 改动内容
> [6f919d1](https://github.com/SHUAXINDIARY/Arknights/commit/6f919d1a2e6da07843f647a5d21c9ea07db64484)
> 
> ### 为什么没有提交 PR
> 截图的TextCard文字错位，图片没有margin
> 
> 例图： ![image](https://private-user-images.githubusercontent.com/115227758/388945991-809cd7ef-1c1f-411c-8685-a0ba99c194a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyODI1OTYsIm5iZiI6MTczMjI4MjI5NiwicGF0aCI6Ii8xMTUyMjc3NTgvMzg4OTQ1OTkxLTgwOWNkN2VmLTFjMWYtNDExYy04Njg1LWEwYmE5OWMxOTRhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxMzMxMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Nzk3MGY1OGI3YjhlNzdlNDRkMjcwNjhjY2Y4ZjYzMmQ0YzZiZmE0MTM0MTI4ZjljMWIyMzFlOTdhODkwYmVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5cmeqQBFkXS6E6qiaMjCAQRVW9RoCHCBFAdRGCfvf2E)
> 
> 如果您有时间，非常感谢你查看我的改动！
> 
> 谢谢！

感谢你的提交！👍🏻；我之前也有尝试用这个库，原因就是样式错了，所以就换成了被你替换的那个🤣 ，结果太模糊了，我就关掉了这个功能，我今天也有在开发这块，feat/add-feature可以看看这分支，我现在变成让domtoimage去把html转成svg，然后用svg再转成图片去绘制到canvas上，然后超采样一下就可以得到非常清晰的图；目前pc和安卓没有问题了，但是Safari上还有点问题，我在解决🤣 感兴趣的话可以在这个分支来看看

**Comment by SHUAXINDIARY** [comment]
> 如题

已经上了

**Comment by SHUAXINDIARY** [comment]
done

**Comment by reKelin** [comment]
![Arknights](https://github.com/user-attachments/assets/4bb914e2-247e-45bd-ad22-848b9d91ef6e)
PC上导出的图空白太多了吧？
像前面 [novelyear](https://github.com/novelyear) 导出的结果一样更合理一点？

**Comment by SHUAXINDIARY** [comment]
> ![Arknights](https://private-user-images.githubusercontent.com/37822901/389195290-4bb914e2-247e-45bd-ad22-848b9d91ef6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNjM4NzUsIm5iZiI6MTczMjM2MzU3NSwicGF0aCI6Ii8zNzgyMjkwMS8zODkxOTUyOTAtNGJiOTE0ZTItMjQ3ZS00NWJkLWFkMjItODQ4YjlkOTFlZjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDEyMDYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNDM1NTQxNGVlMWUxM2NjYjFmNzEyNTBlNGQzNTc5NmY4MmY2ZjlmZGQyNzA2NmQyMGFhMzYxMWI3YWRjMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4wZdtvsr6NcFdXrVPbbbg1L2oMTYbS8fjNHPMY_jRI0) PC上导出的图空白太多了吧？ 像前面 [novelyear](https://github.com/novelyear) 导出的结果一样更合理一点？

主要流量都是在移动端，我取的整个视窗，不然要处理样式问题，感兴趣你可以在优化一下
